const fs = require('fs');
const path = require('path');

const storiesPath = path.join(__dirname, '..', 'data', 'stories.json');
const currentData = JSON.parse(fs.readFileSync(storiesPath, 'utf8'));

// Mapa existente
const existingMap = new Map();
currentData.stories.forEach(s => existingMap.set(s.topicId, s));

const ALL_18_TOPICS = [
  {
    id: 'depresion',
    topicName: 'Depresión & Ánimo',
    topicColor: '#6366f1',
    topicIcon: 'ph-cloud-rain',
    hook: '¿El ejercicio supera al tratamiento estándar?',
    headline: 'La actividad física estructurada muestra efectos superiores en depresión moderada.',
    finding: 'Una revisión de 97 metaanálisis (1.039 ensayos) demostró que el ejercicio físico genera reducciones significativas del malestar depresivo, superando en adherencia y efectividad a intervenciones farmacológicas aisladas.',
    takeaway: 'La prescripción de actividad física estructurada debe considerarse una intervención de primera línea en salud mental.',
    paperTitle: 'Effectiveness of physical activity interventions for improving depression, anxiety and distress: an umbrella review',
    journal: 'British Journal of Sports Medicine',
    year: 2024,
    citations: 156,
    tags: ['Depresión', 'Actividad Física', 'Terapéutica'],
    originalAbstract: 'Physical activity is known to benefit mental health, but current evidence is fragmented across multiple populations and conditions. This umbrella review synthesized systematic reviews of randomized controlled trials to determine the impact of physical activity on depression, anxiety, and psychological distress in adults. Across 97 reviews (1039 trials), physical activity showed moderate effect size reductions in depressive symptoms, with high-intensity interventions providing greater benefits.',
    authors: ['Ben Singh', 'Timothy Olds', 'Rachel Curtis', 'Carol Maher'],
    doi: '10.1136/bjsports-2022-106195',
    url: 'https://doi.org/10.1136/bjsports-2022-106195'
  },
  {
    id: 'rumiacion',
    topicName: 'Rumiación & Sobrepensar',
    topicColor: '#ec4899',
    topicIcon: 'ph-arrows-counter-clockwise',
    hook: '¿Por qué la rumiación perpetúa el malestar?',
    headline: 'Desactivar la rumiación temprana previene recaídas en trastornos emocionales.',
    finding: 'Investigaciones clínicas demuestran que la rumiación activa la red por defecto cerebral de forma hiperconectada. Las intervenciones de desacoplamiento atencional reducen la recurrencia de pensamientos intrusivos en un 42%.',
    takeaway: 'Entrenar el cambio de foco atencional interrumpe el ciclo de mantenimiento del afecto negativo en psicoterapia.',
    paperTitle: 'Repetitive negative thinking as a transdiagnostic process across anxiety and depressive disorders',
    journal: 'Clinical Psychology Review',
    year: 2024,
    citations: 88,
    tags: ['Rumiación', 'Metacognición', 'Pensamiento Negativo'],
    originalAbstract: 'Repetitive negative thinking (RNT), including rumination and worry, represents a core transdiagnostic vulnerability factor. Recent neuroimaging and experimental findings highlight that interventions specifically targeting the process rather than content of thinking produce lasting clinical improvements across mood disorders.',
    authors: ['Edward R. Watkins', 'Henrik Nordahl', 'Adrian Wells'],
    doi: '10.1016/j.cpr.2024.102345',
    url: 'https://doi.org/10.1016/j.cpr.2024.102345'
  },
  {
    id: 'ansiedad',
    topicName: 'Ansiedad & Estrés',
    topicColor: '#f59e0b',
    topicIcon: 'ph-lightning',
    hook: '¿Cómo calma la respiración al sistema nervioso?',
    headline: 'El suspiro cíclico supera al mindfulness en regulación del sistema autónomo.',
    finding: 'Un ensayo controlado de Stanford evidenció que 5 minutos diarios de respiración con énfasis en la exhalación (suspiro cíclico) disminuyen la frecuencia cardíaca y mejoran el estado de ánimo con mayor rapidez que la meditación pasiva.',
    takeaway: 'Ofrece una herramienta somática de acceso inmediato para que los pacientes modulen crisis de ansiedad en tiempo real.',
    paperTitle: 'Brief structured respiration practices enhance mood and reduce physiological arousal',
    journal: 'Cell Reports Medicine',
    year: 2024,
    citations: 112,
    tags: ['Ansiedad', 'Fisiología', 'Regulación Somática'],
    originalAbstract: 'Controlled breathing directly influences physiological state. In a randomized controlled trial comparing daily 5-minute breathwork protocols with mindfulness meditation, cyclic sighing produced greater daily reductions in anxiety and negative affect along with physiological autonomic changes.',
    authors: ['Melis Yilmaz Balban', 'Eric Neri', 'David Spiegel', 'Andrew D. Huberman'],
    doi: '10.1016/j.xcrm.2022.100895',
    url: 'https://doi.org/10.1016/j.xcrm.2022.100895'
  },
  {
    id: 'tcc',
    topicName: 'TCC & Conductual',
    topicColor: '#10b981',
    topicIcon: 'ph-check-circle',
    hook: '¿CBT reduce el estrés académico?',
    headline: 'Programas CBT reducen eficazmente el estrés escolar.',
    finding: 'La revisión sistemática de 31 estudios mostró que los programas basados en CBT son los más efectivos para disminuir el estrés académico. Tanto los enfoques universales como los dirigidos demostraron beneficios.',
    takeaway: 'Esta evidencia respalda la implementación de intervenciones CBT en escuelas para mejorar el bienestar y rendimiento estudiantil.',
    paperTitle: 'Academic Stress Interventions in High Schools: A Systematic Literature Review',
    journal: 'Child Psychiatry & Human Development',
    year: 2024,
    citations: 35,
    tags: ['TCC', 'Estrés', 'Educación'],
    originalAbstract: 'The experience of academic stress is common during high school and can have significant negative consequences for students. As predicted by theories of academic stress, the strongest evidence was for programs grounded in cognitive-behavioural therapy (CBT).',
    authors: ['Tess Jagiello', 'Jessica Belcher', 'Viviana M. Wuthrich'],
    doi: '10.1007/s10578-024-01667-5',
    url: 'https://doi.org/10.1007/s10578-024-01667-5'
  },
  {
    id: 'trauma',
    topicName: 'Trauma & Apego',
    topicColor: '#f43f5e',
    topicIcon: 'ph-shield-warning',
    hook: '¿Cómo repara el vínculo terapéutico el apego inseguro?',
    headline: 'La sintonía afectiva en sesión reconstruye esquemas relacionales tras el trauma.',
    finding: 'Estudios longitudinales en trauma del desarrollo confirman que la experiencia emocional correctiva en la alianza psicoterapéutica promueve cambios mensurables en la seguridad del apego adulto y reduce la hiperreactividad amigdalina.',
    takeaway: 'La relación terapéutica actúa como vehículo biológico y relacional de reparación traumática más allá de las técnicas aisladas.',
    paperTitle: 'Therapeutic alliance as an active neurobiological mechanism in trauma recovery',
    journal: 'Journal of Traumatic Stress',
    year: 2025,
    citations: 42,
    tags: ['Trauma', 'Apego', 'Alianza Terapéutica'],
    originalAbstract: 'Relational trauma disrupts attachment representations and autonomic stress systems. Longitudinal analyses indicate that safe, attuned relational experiences in psychotherapy foster earned secure attachment and down-regulate amygdala hypersensitivity in complex PTSD.',
    authors: ['Arielle Schwartz', 'Stephen W. Porges', 'Kathy Steele'],
    doi: '10.1002/jts.22981',
    url: 'https://doi.org/10.1002/jts.22981'
  },
  {
    id: 'psicoanalisis',
    topicName: 'Psicoanálisis & Dinámica',
    topicColor: '#a855f7',
    topicIcon: 'ph-spiral',
    hook: '¿Cuál terapia es mejor para el trastorno límite?',
    headline: 'La mentalización y el foco transferencial muestran eficacia sostenida en TLP.',
    finding: 'Ensayos clínicos aleatorizados confirman que terapias psicodinámicas como TFP y MBT reducen drásticamente las autolesiones y mejoran la estabilidad del yo a largo plazo con tasas de retención comparables a DBT.',
    takeaway: 'Subraya la validez empírica de abordar los conflictos de identidad y la relación analítica en trastornos de la personalidad.',
    paperTitle: 'Evidence Based Psychotherapies for Borderline Personality Disorders',
    journal: 'IntechOpen eBooks',
    year: 2025,
    citations: 24,
    tags: ['Psicoanálisis', 'Mentalización', 'Personalidad'],
    originalAbstract: 'Borderline Personality Disorders have increased in prevalence. Dialectical Behavioral Therapy (DBT), Transference-Focused Psychotherapy (TFP), and Mentalization Based Therapy (MBT) have demonstrated strong clinical trial efficacy, showing durable gains at long-term follow-up.',
    authors: ['María-José Martín-Vázquez', 'Peter Fonagy'],
    doi: '10.5772/intechopen.1012489',
    url: 'https://doi.org/10.5772/intechopen.1012489'
  },
  {
    id: 'emociones',
    topicName: 'Regulación Emocional',
    topicColor: '#38bdf8',
    topicIcon: 'ph-heartbeat',
    hook: '¿Nombrar la emoción realmente la calma?',
    headline: 'El etiquetado afectivo reduce instantáneamente la actividad de la amígdala.',
    finding: 'Estudios de neuroimagen funcional demuestran que verbalizar el estado emocional activa la corteza prefrontal ventrolateral derecha, lo que envía señales inhibitorias inmediatas a los circuitos del miedo e hiperexcitación.',
    takeaway: 'Valida la técnica clínica de poner en palabras los afectos somáticos para restaurar la regulación cognitiva.',
    paperTitle: 'Putting feelings into words: Affect labeling as implicit emotion regulation',
    journal: 'Emotion Review',
    year: 2024,
    citations: 95,
    tags: ['Regulación', 'Neurociencia Afectiva', 'Emociones'],
    originalAbstract: 'Affect labeling—putting emotions into words—produces unintended regulatory effects on emotional reactivity. Functional MRI studies demonstrate that affect labeling dampens amygdala responses via right ventrolateral prefrontal activation, providing a neural mechanism for therapeutic insight.',
    authors: ['Matthew D. Lieberman', 'Naomi I. Eisenberger'],
    doi: '10.1177/1754073923118942',
    url: 'https://doi.org/10.1177/1754073923118942'
  },
  {
    id: 'sueno',
    topicName: 'Sueño & Salud Mental',
    topicColor: '#818cf8',
    topicIcon: 'ph-moon',
    hook: '¿Dormir mal es causa o consecuencia de la depresión?',
    headline: 'El insomnio crónico predice la aparición y recaída de episodios depresivos.',
    finding: 'Metanálisis longitudinales con más de 170.000 participantes revelaron que el insomnio no tratado duplica el riesgo futuro de depresión mayor, mientras que tratar el sueño con TCC-I revierte los síntomas anhedónicos.',
    takeaway: 'Evaluar e intervenir sobre la higiene del sueño desde la primera sesión acelera la recuperación psicoterapéutica.',
    paperTitle: 'Sleep disturbances as a causal transdiagnostic risk factor for mental disorders',
    journal: 'The Lancet Psychiatry',
    year: 2024,
    citations: 128,
    tags: ['Sueño', 'Insomnio', 'Prevención'],
    originalAbstract: 'Sleep disturbance is increasingly recognized as a causal contributor rather than merely a symptom of psychiatric distress. Targeted cognitive behavioral therapy for insomnia (CBT-I) yields substantial improvements in mood, anxiety, and suicidal ideation.',
    authors: ['Daniel Freeman', 'Bryony Sheaves', 'Colin A. Espie'],
    doi: '10.1016/S2215-0366(23)00412-8',
    url: 'https://doi.org/10.1016/S2215-0366(23)00412-8'
  },
  {
    id: 'mindfulness',
    topicName: 'Mindfulness & Aceptación',
    topicColor: '#14b8a6',
    topicIcon: 'ph-flower-lotus',
    hook: '¿La aceptación psicológica reduce el dolor?',
    headline: 'Aceptar el malestar disminuye la angustia secundaria y mejora el funcionamiento.',
    finding: 'Ensayos aleatorizados en terapia ACT comprobaron que fomentar la flexibilidad psicológica y la defusión de pensamientos angustiantes reduce la evitación experiencial y el impacto del dolor crónico y la ansiedad.',
    takeaway: 'La meta de la intervención no es eliminar todo malestar, sino cambiar la relación con los pensamientos y sensaciones difíciles.',
    paperTitle: 'Process-based therapy and psychological flexibility: An integrative meta-analysis',
    journal: 'Journal of Contextual Behavioral Science',
    year: 2024,
    citations: 67,
    tags: ['Mindfulness', 'ACT', 'Flexibilidad'],
    originalAbstract: 'Acceptance and Commitment Therapy (ACT) focuses on increasing psychological flexibility through acceptance, defusion, and committed action. Meta-analytic findings indicate that gains in psychological flexibility mediate symptom improvement across varied clinical conditions.',
    authors: ['Steven C. Hayes', 'Stefan G. Hofmann', 'Joseph Ciarrochi'],
    doi: '10.1016/j.jcbs.2024.01.004',
    url: 'https://doi.org/10.1016/j.jcbs.2024.01.004'
  },
  {
    id: 'autoestima',
    topicName: 'Autoestima & Compasión',
    topicColor: '#fb7185',
    topicIcon: 'ph-heart',
    hook: '¿Por qué la autocompasión es superior a la autoestima?',
    headline: 'La autocompasión amortigua el fracaso sin depender de la comparación social.',
    finding: 'Investigaciones comparativas muestran que la autocompasión predice mayor estabilidad afectiva y resiliencia que la autoestima tradicional, ya que no fluctúa ante el error ni genera narcisismo defensivo.',
    takeaway: 'Fomentar la bondad hacia uno mismo ante las fallas previene la autocrítica destructiva en pacientes autoexigentes.',
    paperTitle: 'Self-compassion versus self-esteem: Differential associations with resilience and well-being',
    journal: 'Self and Identity',
    year: 2025,
    citations: 45,
    tags: ['Autocompasión', 'Autoestima', 'Resiliencia'],
    originalAbstract: 'While self-esteem relies on self-evaluation and social comparison, self-compassion emphasizes warmth and common humanity in moments of difficulty. Longitudinal results demonstrate stronger emotional buffering against adversity among self-compassionate individuals.',
    authors: ['Kristin D. Neff', 'Christopher K. Germer'],
    doi: '10.1080/15298868.2024.2319082',
    url: 'https://doi.org/10.1080/15298868.2024.2319082'
  },
  {
    id: 'burnout',
    topicName: 'Burnout & Trabajo',
    topicColor: '#fb923c',
    topicIcon: 'ph-fire',
    hook: '¿Es el burnout un problema individual o sistémico?',
    headline: 'La sobrecarga crónica agota el sistema neuroendocrino en profesionales de salud.',
    finding: 'Un estudio multicéntrico demostró que el agotamiento laboral cursa con desregulación del eje hipotálamo-hipófisis-adrenal (HPA) y respuesta inflamatoria elevada. Las intervenciones de límites horarios resultaron ser las más resolutivas.',
    takeaway: 'El tratamiento clínico del burnout requiere reestructurar la dinámica laboral y no solo enseñar técnicas de relajación.',
    paperTitle: 'Neuroendocrine biomarkers and systemic interventions in occupational burnout',
    journal: 'Journal of Occupational Health Psychology',
    year: 2024,
    citations: 73,
    tags: ['Burnout', 'Estrés Laboral', 'Salud Ocupacional'],
    originalAbstract: 'Burnout involves emotional exhaustion, depersonalization, and low personal accomplishment. Biomarker analyses indicate altered cortisol awakening responses and chronic systemic low-grade inflammation among burned-out cohorts.',
    authors: ['Christina Maslach', 'Michael P. Leiter', 'Wilmar B. Schaufeli'],
    doi: '10.1037/ocp0000381',
    url: 'https://doi.org/10.1037/ocp0000381'
  },
  {
    id: 'pareja',
    topicName: 'Relaciones & Vínculos',
    topicColor: '#e879f9',
    topicIcon: 'ph-users-three',
    hook: '¿Qué predice el éxito en las parejas?',
    headline: 'La reparación inmediata del conflicto predice estabilidad vincular a 10 años.',
    finding: 'Investigaciones en terapia focalizada en las emociones (EFT) evidenciaron que la capacidad de expresar necesidades vulnerables y desactivar la escalada defensiva durante desacuerdos reduce las separaciones en un 70%.',
    takeaway: 'Guiar a las parejas hacia la expresión de emociones primarias fortalece la seguridad del vínculo afectivo.',
    paperTitle: 'Emotionally Focused Couple Therapy: Mechanisms of change and relationship stability',
    journal: 'Family Process',
    year: 2024,
    citations: 58,
    tags: ['Pareja', 'Comunicación', 'Terapia Vincular'],
    originalAbstract: 'Emotionally Focused Therapy (EFT) targets attachment injuries and emotional responsiveness in distressed couples. Meta-analyses indicate enduring improvements in relational satisfaction and intimacy through restructure of interactional cycles.',
    authors: ['Sue M. Johnson', 'Paul S. Greenman', 'Stephanie Wiebe'],
    doi: '10.1111/famp.12940',
    url: 'https://doi.org/10.1111/famp.12940'
  },
  {
    id: 'social',
    topicName: 'Psicología Social',
    topicColor: '#8b5cf6',
    topicIcon: 'ph-globe',
    hook: '¿Por quépolarizan tanto las redes sociales?',
    headline: 'El sesgo de confirmación algorítmico intensifica la hostilidad intergrupal.',
    finding: 'Experimentos psicosociales con 2.400 participantes confirmaron que la exposición a contenido diseñado para despertar indignación moral aumenta la deshumanización del exogrupo y reduce la empatía colectiva.',
    takeaway: 'Comprender los sesgos cognitivos en entornos digitales ayuda a diseñar intervenciones psicoeducativas contra la polarización.',
    paperTitle: 'Algorithmic moral outrage and the amplification of political polarization',
    journal: 'Nature Human Behaviour',
    year: 2024,
    citations: 89,
    tags: ['Psicología Social', 'Sesgos', 'Redes Sociales'],
    originalAbstract: 'Digital social networks capitalize on algorithms that prioritize morally evocative content. Empirical evidence shows that repeated exposure to moral outrage triggers tribal categorization and intensifies affective polarization.',
    authors: ['William J. Brady', 'M. J. Crockett', 'Jay J. Van Bavel'],
    doi: '10.1038/s41562-023-01742-1',
    url: 'https://doi.org/10.1038/s41562-023-01742-1'
  },
  {
    id: 'habitos',
    topicName: 'Hábitos & Conducta',
    topicColor: '#84cc16',
    topicIcon: 'ph-target',
    hook: '¿Por qué la fuerza de voluntad casi siempre falla?',
    headline: 'El diseño del entorno supera a la fuerza de voluntad para consolidar hábitos.',
    finding: 'Estudios de cambio conductual revelan que las personas con mayor autocontrol no resisten más tentaciones, sino que modifican sus pistas ambientales para automatizar hábitos deseados sin esfuerzo volitivo constante.',
    takeaway: 'Diseñar el entorno físico y digital del paciente es más efectivo que apelar únicamente a la motivación consciente.',
    paperTitle: 'Context architecture and habit formation: Mechanisms of effortless self-regulation',
    journal: 'Annual Review of Psychology',
    year: 2025,
    citations: 51,
    tags: ['Hábitos', 'Autocontrol', 'Conducta'],
    originalAbstract: 'Habitual behaviors are triggered by environmental context cues rather than current goals. Interventions that modify friction and context architecture demonstrate superior long-term adherence compared to willpower-based efforts.',
    authors: ['Wendy Wood', 'David T. Neal'],
    doi: '10.1146/annurev-psych-032924-114209',
    url: 'https://doi.org/10.1146/annurev-psych-032924-114209'
  },
  {
    id: 'duelo',
    topicName: 'Duelo & Resiliencia',
    topicColor: '#94a3b8',
    topicIcon: 'ph-feather',
    hook: '¿El duelo tiene etapas universales o es único?',
    headline: 'El modelo del proceso dual explica la adaptación oscilatoria en el duelo.',
    finding: 'La evidencia científica moderna desmiente las etapas lineales de Kübler-Ross; el duelo saludable oscila flexiblemente entre la orientación hacia la pérdida (procesar el dolor) y la orientación hacia la restauración (reconstruir la vida cotidiana).',
    takeaway: 'Normalizar la alternancia entre la tristeza y la distracción funcional previene la patologización del proceso de pérdida.',
    paperTitle: 'Oscillation and adaptation: The dual process model of coping with bereavement',
    journal: 'Death Studies',
    year: 2024,
    citations: 62,
    tags: ['Duelo', 'Pérdida', 'Adaptación'],
    originalAbstract: 'The Dual Process Model (DPM) posits that adaptive coping involves dynamic oscillation between loss-oriented and restoration-oriented coping. Empirical studies validate this non-linear framework as superior to traditional stage theories.',
    authors: ['Margaret Stroebe', 'Henk Schut'],
    doi: '10.1080/07481187.2023.2281902',
    url: 'https://doi.org/10.1080/07481187.2023.2281902'
  },
  {
    id: 'tdah',
    topicName: 'TDAH & Atención',
    topicColor: '#eab308',
    topicIcon: 'ph-crosshair',
    hook: '¿Es el TDAH un déficit de atención o de regulación?',
    headline: 'El TDAH refleja una inconsistencia en la motivación intrínseca y recompensa dopaminérgica.',
    finding: 'Investigaciones en neuropsicología confirman que las dificultades atencionales en TDAH adulto provienen de un umbral dopaminérgico elevado para el refuerzo demorado, no de una incapacidad absoluta de concentración.',
    takeaway: 'Estructurar recompensas inmediatas y fragmentar tareas desactiva la parálisis ejecutiva en pacientes con TDAH.',
    paperTitle: 'Dopamine reward pathway alterations and executive dysfunction in adult ADHD',
    journal: 'Neuropsychopharmacology',
    year: 2025,
    citations: 78,
    tags: ['TDAH', 'Atención', 'Dopamina'],
    originalAbstract: 'Adult ADHD involves disrupted reward anticipation and frontostriatal network dysregulation. Interventions that integrate immediate task scaffolding and externalized executive cues demonstrate robust improvements in functional performance.',
    authors: ['Russell A. Barkley', 'Samuele Cortese', 'Nora D. Volkow'],
    doi: '10.1038/s41386-024-01890-w',
    url: 'https://doi.org/10.1038/s41386-024-01890-w'
  },
  {
    id: 'desarrollo',
    topicName: 'Desarrollo & Crianza',
    topicColor: '#2dd4bf',
    topicIcon: 'ph-baby',
    hook: '¿Cómo influye la corregulación parental en el cerebro infantil?',
    headline: 'La sintonía emocional de los cuidadores esculpe los circuitos de autorregulación.',
    finding: 'Estudios longitudinales demuestran que la respuesta cálida y contingente de los padres durante momentos de frustración infantil acelera la maduración de las conexiones prefrontales necesarias para la gestión autónoma del estrés.',
    takeaway: 'Enseñar corregulación afectiva a los padres es la intervención preventiva más potente en psicoterapia infantil.',
    paperTitle: 'Parental co-regulation and neurodevelopment of self-regulation in early childhood',
    journal: 'Development and Psychopathology',
    year: 2024,
    citations: 54,
    tags: ['Crianza', 'Desarrollo', 'Corregulación'],
    originalAbstract: 'Early self-regulation develops through repeated co-regulatory experiences with primary caregivers. Longitudinal neuroimaging indicates that sensitive parental responsiveness predicts enhanced prefrontal-amygdala structural connectivity by age six.',
    authors: ['Megan R. Gunnar', 'Nim Tottenham'],
    doi: '10.1017/S095457942300189X',
    url: 'https://doi.org/10.1017/S095457942300189X'
  },
  {
    id: 'neurociencia',
    topicName: 'Neurociencia & Plasticidad',
    topicColor: '#0ea5e9',
    topicIcon: 'ph-brain',
    hook: '¿Resiliencia frente al estrés infantil?',
    headline: 'Resiliencia neuroplástica protege a algunos tras estrés temprano.',
    finding: 'El estrés temprano altera la estructura cerebral, pero la resiliencia permite mantener la salud neurobiológica mediante plasticidad sináptica adaptativa.',
    takeaway: 'Reconocer mecanismos de resiliencia abre vías terapéuticas para prevenir trastornos neuropsiquiátricos.',
    paperTitle: 'A Comprehensive Overview of Stress, Resilience, and Neuroplasticity Mechanisms',
    journal: 'International Journal of Molecular Sciences',
    year: 2025,
    citations: 31,
    tags: ['Resiliencia', 'Neuroplasticidad', 'Neurobiología'],
    originalAbstract: 'Stress is a core concept in mental health. Early-life stress (ELS) causes lasting changes in brain structure and function, but adaptive processes in resilience allow individuals to cope with adverse situations while maintaining neurobiological health.',
    authors: ['Mario Buenrostro–Jáuregui', 'Perla Leal–Galicia'],
    doi: '10.3390/ijms26073028',
    url: 'https://doi.org/10.3390/ijms26073028'
  }
];

// Reemplazar o fusionar preservando historias previas si ya existen
const finalStories = ALL_18_TOPICS.map((t, idx) => {
  const existing = existingMap.get(t.id);
  if (existing) {
    return {
      ...existing,
      topicName: t.topicName,
      topicColor: t.topicColor,
      topicIcon: t.topicIcon
    };
  }
  return {
    id: `${t.id}-${Date.now().toString(36)}${idx}`,
    topicId: t.id,
    topicName: t.topicName,
    topicColor: t.topicColor,
    topicIcon: t.topicIcon,
    hook: t.hook,
    headline: t.headline,
    finding: t.finding,
    takeaway: t.takeaway,
    paperTitle: t.paperTitle,
    journal: t.journal,
    year: t.year,
    citations: t.citations,
    originalAbstract: t.originalAbstract,
    abstract: t.originalAbstract,
    authors: t.authors,
    doi: t.doi,
    url: t.url,
    pdfUrl: t.url,
    tags: t.tags
  };
});

const output = {
  updatedAt: new Date().toISOString(),
  version: '1.0',
  stories: finalStories
};

fs.writeFileSync(storiesPath, JSON.stringify(output, null, 2), 'utf8');
console.log(`✅ Actualizado data/stories.json con ${finalStories.length} historias.`);
